version: "3.6"

networks:
  ha-stack:
    ipam:
      config:
        - subnet: 172.20.0.0/24

services:
  runner:
    image: "runner:local"
    build:
      context: .
    networks:
      - ha-stack

  keepalived-a:
    image: "osixia/keepalived:2.0.17"
    networks:
      ha-stack:
        ipv4_address: 172.20.0.30
    cap_add:
      - NET_ADMIN
      - NET_BROADCAST
      - NET_RAW
    environment:
      KEEPALIVED_COMMAND_LINE_ARGUMENTS: >-
        --log-detail
    volumes:
      - "./keepalived/proxy-a/keepalived.conf:/usr/local/etc/keepalived/keepalived.conf:ro"
      - "./keepalived/notify.sh:/container/service/keepalived/assets/notify.custom.sh:ro"

  keepalived-b:
    image: "osixia/keepalived:2.0.17"
    networks:
      ha-stack:
        ipv4_address: 172.20.0.40
    cap_add:
      - NET_ADMIN
      - NET_BROADCAST
      - NET_RAW
    environment:
      KEEPALIVED_COMMAND_LINE_ARGUMENTS: >-
        --log-detail
      # KEEPALIVED_COMMAND_LINE_ARGUMENTS: >-
      #   -–dont-release-vrrp
      #   -–dont-release-ipvs
      #   --log-detail
      #   --dump-conf
    volumes:
      - "./keepalived/proxy-b/keepalived.conf:/usr/local/etc/keepalived/keepalived.conf:ro"
      - "./keepalived/notify.sh:/container/service/keepalived/assets/notify.custom.sh:ro"

  haproxy-a:
    image: "haproxy:2.0-alpine"
    networks:
      ha-stack:
        ipv4_address: 172.20.0.50
        aliases:
          - haproxy-a.ha.stack
    cap_add:
      - NET_ADMIN
      - NET_BROADCAST
      - NET_RAW
    volumes:
      - "./haproxy/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro"

  haproxy-b:
    image: "haproxy:2.0-alpine"
    networks:
      ha-stack:
        ipv4_address: 172.20.0.60
        aliases:
          - haproxy-b.ha.stack
    cap_add:
      - NET_ADMIN
      - NET_BROADCAST
      - NET_RAW
    volumes:
      - "./haproxy/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro"

  web-b:
    image: "nginx:stable-alpine"
    networks:
      ha-stack:
        aliases:
          - web-b.ha.stack
    volumes:
      - "./web/server-b/index.html:/usr/share/nginx/html/index.html:ro"

  web-a:
    image: "nginx:stable-alpine"
    networks:
      ha-stack:
        aliases:
          - web-a.ha.stack
    volumes:
      - "./web/server-a/index.html:/usr/share/nginx/html/index.html:ro"
